name: Revelar Secret Temporal

on:
  workflow_dispatch:

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar Secret Separado
        env:
          MI_SECRET: ${{ secrets.TIENDANUBE_ACCESS_TOKEN }}
        run: |
          echo "Tu secret token es:"
          echo "$MI_SECRET" | sed 's/./& /g'
