name: Revelar Secret Temporal

on:
  workflow_dispatch: # Permite ejecutarlo manualmente desde la pestaña Actions

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar Secret en Base64
        env:
          MI_SECRET: ${{ secrets.NOMBRE_DE_TU_SECRET }}
        run: |
          echo "Secret en Base64:"
          echo -n "$MI_SECRET" | base64
